background-color=#20201dFF
text-color=#a6a28cFF
border-color=#6684e1FF
progress-color=#6684e1FF

[urgency=low]
background-color=#20201dFF
text-color=#7d7a68FF
border-color=#292824FF

[urgency=normal]
background-color=#20201dFF
text-color=#a6a28cFF
border-color=#6684e1FF

[urgency=critical]
background-color=#6e6b5e
text-color=#fefbecFF
border-color=#d43552FF
default-timeout=0
